### ISSUE TITLE
error on load

### ISSUE THREAD

**Issue by iccor56** [ReikaKalseki/Reika_FactorioMods_Issues#167] opened 2019-06-12 05:04 UTC
![Capture](https://user-images.githubusercontent.com/11468128/59324735-3309f700-8cae-11e9-940e-510c95c7d70a.PNG)

error on load when i tried it today (1am). just uploaded to 1.17.6.

also the heat exchangers have been invisible since .17 was made. still work just can't see them.

**Comment by ReikaKalseki** [comment] 2019-06-13 21:24
I have fixed the first issue already, and it is a duplicate of #138 and more.

As for invisible heat exchangers, that is new, and also makes no sense. Are you sure it is not just you running out of VRAM, which has effects like that?

**Comment by ReikaKalseki** [comment] 2019-09-30 05:01
Hello?

**Closed as completed** 2020-06-12 16:05 UTC
Labels: Information Never Provided
